# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20190514_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['content']},
        ),
    ]
