# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20190514_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet'),
            preserve_default=False,
        ),
    ]
