# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0017_tweet_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=130),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='reply',
            field=models.BooleanField(default=True, verbose_name='Is a Reply ?'),
        ),
    ]
